version: "3"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NAPython
    ports:
      - "5000:5000"
    volumes:
      - .:/home/nutriappapi
    environment:
      - FLASK_APP=App/main.py
      - FLASK_DEBUG=1
